# Get all todos
GET {{host}}/api/todos
Accept: */*
User-Agent: VS-Code

###

# Create a todo
POST {{host}}/api/todos
Accept: */*
User-Agent: VS-Code
Content-Type: application/json

{
    "body":"hello world"
}

###

# Complete a todo
PATCH {{host}}/api/todos/2
Accept: */*
User-Agent: VS-Code
Content-Type: application/application/json

###

# Delete a todo
DELETE {{host}}/api/todos/2
Accept: */*
User-Agent: VS-Code
Content-Type: application/application/json