# Get heatmap
POST {{host}}/api/safetyheatmap/heatmap/get
Accept: */*
User-Agent: VS-Code
Content-Type: application/json

{
	"size": "S",
    "range": {
        "topleft": {
            "lat": -100,
            "lng": -100
        },
        "bottomright": {
            "lat": 100,
            "lng": 100
        }
    }
}

###

# Create a report
POST {{host}}/api/safetyheatmap/report/add
Accept: */*
User-Agent: VS-Code
Content-Type: application/json

{
    "lat":2,
    "lng":2
}